MACRO(INITNG_MODULE target)
	ADD_LIBRARY(${target} MODULE ${ARGN})
	TARGET_LINK_LIBRARIES(${target} initng)
	SET_TARGET_PROPERTIES(${target} PROPERTIES
		LINK_FLAGS    ${MOD_LDFLAGS}
		COMPILE_FLAGS ${MOD_CFLAGS}
		PREFIX        "mod"
	)
ENDMACRO(INITNG_MODULE target)
