MACRO(INITNG_MODULE target)
	ADD_LIBRARY(${target} MODULE ${ARGN})
	TARGET_LINK_LIBRARIES(${target} initng)
	SET_TARGET_PROPERTIES(also PROPERTIES
		LINK_FLAGS    ${MOD_FLAGS}
		COMPILE_FLAGS ${MOD_CFLAGS}
		PREFIX        "mod"
	)
ENDMACRO(initng_module)
