#!/bin/sh

eval "
${COMMAND}()
{
	echo \"${SERVICE}: command ${COMMAND} not found.\"
	return 1
}
"

ireg()
{
	[ -n "${2}" ] && export SERVICE="${2}"
	iregister "${1}" || exit 1
}

export PATH="@LIB_INSTALL_DIR@/ibin:${PATH}"
source "${SERVICE_FILE}"

${COMMAND}
